import Enum from '../utils/enum';

export const usersCategoriesActionTypes = Enum({
    FETCH_USERS_CATEGORIES: 'FETCH_USERS_CATEGORIES',
    FETCH_USERS_CATEGORIES_SUCCESS: 'FETCH_USERS_CATEGORIES_SUCCESS',
    FETCH_USERS_CATEGORIES_ERROR: 'FETCH_USERS_CATEGORIES_ERROR'
});