import Enum from '../utils/enum';

export const assetCategoriesActionTypes = Enum({
    FETCH_ASSET_CATEGORIES: 'FETCH_ASSET_CATEGORIES',
    FETCH_ASSET_CATEGORIES_SUCCESS: 'FETCH_ASSET_CATEGORIES_SUCCESS',
    FETCH_ASSET_CATEGORIES_ERROR: 'FETCH_ASSET_CATEGORIES_ERROR'
});